// // import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }: LayoutProps<"/">) {
// //   return (
// //     <html
// //       lang="en"
// //       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
// //     >
// //       <body className="min-h-full flex flex-col">{children}</body>
// //     </html>
// //   );
// // }

// import type { Metadata } from "next";
// import "./globals.css";
// import ThemeProvider from "@/components/ThemeProvider";

// export const metadata: Metadata = {
//   title: "AI Chatbot",
//   description: "Generic AI chatbot powered by OpenRouter",
// };

// // Runs before React hydrates so the correct theme is applied immediately.
// const themeInitScript = `
// (function() {
//   try {
//     var stored = localStorage.getItem('theme');
//     var prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
//     var theme = stored || (prefersDark ? 'dark' : 'light');
//     if (theme === 'dark') document.documentElement.classList.add('dark');
//   } catch (e) {}
// })();
// `;

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <head>
//         <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
//       </head>
//       <body className="bg-white text-gray-900 dark:bg-gray-950 dark:text-gray-100 antialiased">
//         <ThemeProvider>{children}</ThemeProvider>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/components/ThemeProvider";
import AuthProvider from "@/components/AuthProvider";

export const metadata: Metadata = {
  title: "AI Chatbot",
  description: "Generic AI chatbot powered by OpenRouter",
};

const themeInitScript = `
(function() {
  try {
    var stored = localStorage.getItem('theme');
    var prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    var theme = stored || (prefersDark ? 'dark' : 'light');
    if (theme === 'dark') document.documentElement.classList.add('dark');
  } catch (e) {}
})();
`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body className="bg-white text-gray-900 dark:bg-gray-950 dark:text-gray-100 antialiased">
        <ThemeProvider>
          <AuthProvider>{children}</AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}